# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildJava-BuildPushDocker:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: salazro69/demo-app
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  Deploy-In-Minikube:
    runs-on: ubuntu-latest
    needs: BuildJava-BuildPushDocker

    steps:
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Get k8s Component Status
        run: kubectl get componentstatuses

      - name: Check the health of the API endpoints
        run: kubectl get --raw='/readyz?verbose'
 
      - name: Check Node Status
        run: kubectl get nodes

      - name: Describe Nodes
        run: kubectl describe nodes minikube
      
      - name: Create Deployment
        run: kubectl create deployment gradle-minikube --image=salazro69/demo-app:latest --replicas=3

      - name: Check ReplicaSets
        run: kubectl get replicasets

      - name: Check Services
        run: kubectl get services

      - name: Waiting for container creation (delay)
        run: sleep 20s
        shell: bash
      
      - name: Check Pod Status
        run: kubectl get pods
    
         
